"""create core schema

Revision ID: 5d79256e586a
Revises:
Create Date: 2026-05-25 12:13:24.271338
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '5d79256e586a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('current_objective', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('email_or_contact_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=255), nullable=False),
    sa.Column('response_reference_type', sa.String(length=128), nullable=True),
    sa.Column('response_reference_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'idempotency_key', name='uq_idempotency_records_scope_key')
    )
    op.create_table('kill_switch_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('activated_by_actor', sa.String(length=255), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_by_actor', sa.String(length=255), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_reference', name='uq_leads_source_reference')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('reference_type', sa.String(length=128), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'append_only_mvp_guard': 'no update/delete columns; DB trigger deferred'}
    )
    op.create_index('ix_ledger_entries_reference', 'ledger_entries', ['reference_type', 'reference_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('allowed_channels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('rule_results', sa.JSON(), nullable=False),
    sa.Column('request_reference_type', sa.String(length=128), nullable=False),
    sa.Column('request_reference_id', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_by_actor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type in ('revenue', 'operating', 'reserve')", name='ck_wallets_type_mvp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'currency', name='uq_wallets_type_currency')
    )
    op.create_table('checkout_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('payment_provider', sa.String(length=128), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_checkout_sessions_idempotency_key'),
    sa.UniqueConstraint('payment_provider', 'provider_reference', name='uq_checkout_sessions_provider_reference')
    )
    op.create_table('exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=128), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=False),
    sa.Column('policy_decision_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('policy_status', sa.String(length=64), nullable=False),
    sa.Column('policy_decision_id', sa.String(length=36), nullable=True),
    sa.Column('source_wallet_id', sa.String(length=36), nullable=True),
    sa.Column('execution_status', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_by_actor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], ),
    sa.ForeignKeyConstraint(['source_wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_expense_requests_idempotency_key')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('offer_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('payment_provider', sa.String(length=128), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_provider', 'provider_reference', name='uq_invoices_provider_reference')
    )
    op.create_table('wallet_transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_wallet_id', sa.String(length=36), nullable=False),
    sa.Column('destination_wallet_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('policy_decision_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destination_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], ),
    sa.ForeignKeyConstraint(['source_wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_wallet_transfers_idempotency_key')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checkout_session_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('payment_provider', sa.String(length=128), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('settlement_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['checkout_session_id'], ['checkout_sessions.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_payments_idempotency_key'),
    sa.UniqueConstraint('payment_provider', 'provider_reference', name='uq_payments_provider_reference')
    )
    op.create_table('bucket_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('source_wallet_id', sa.String(length=36), nullable=False),
    sa.Column('destination_wallet_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('allocation_rule_reference', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destination_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['source_wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_bucket_allocations_idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucket_allocations')
    op.drop_table('payments')
    op.drop_table('wallet_transfers')
    op.drop_table('invoices')
    op.drop_table('expense_requests')
    op.drop_table('exceptions')
    op.drop_table('checkout_sessions')
    op.drop_table('wallets')
    op.drop_table('reports')
    op.drop_table('policy_rules')
    op.drop_table('policy_decisions')
    op.drop_table('offers')
    op.drop_index('ix_ledger_entries_reference', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('leads')
    op.drop_table('kill_switch_states')
    op.drop_table('idempotency_records')
    op.drop_table('customers')
    op.drop_table('agents')
    # ### end Alembic commands ###
